[package]
name = "webauth"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows = { version = "0.62.0", features = [
    "Win32_Graphics_Gdi",
    "Win32_Security_Credentials",
    "Win32_System_Com",
    "Win32_UI_Shell",
] }
windows-core = "0.62.0"
